spring:
  web:
    resources:
      static-locations:
#        - classpath:/static/
#        - classpath:/Users/netsquire/stage/kg-ui/
        - file:/Users/netsquire/stage/kg-ui
        - file:/var/www/shared/
  mvc:
    static-path-pattern: /**